docker/populate
docker/subpopulate.py
docs/prerequisites.md

Closes #282, this pr adds the --wsl flag for wsl users. Can one of you guys try it out and see if it works accordingly?
@NielsPraet @NinjaJay @TomAlard @tvhimme

Populate script for wsl

---

.github/workflows/all_tests.yml

all_tests didn't have working dir and didn't find the script

Quick actions fix

---

frontend/components/editions/EditionDeletionPopup.tsx
frontend/pages/editions.tsx

**New feature checklist**:
Closes #262

Editions uiux

---

backend/src/main/kotlin/be/osoc/team1/backend/services/ProjectService.kt
backend/src/main/kotlin/be/osoc/team1/backend/util/Serializers.kt
backend/src/test/kotlin/be/osoc/team1/backend/unittests/ProjectServiceTests.kt
docs/osoc.yaml

Closes #334.
**Breaking change checklist**:

Fix conflict endpoint URLs

---

frontend/pages/login.tsx

Remove log in using GitHub

---

frontend/pages/login.tsx

Closes #336.
The user is now redirected to the projects page if there is an active edition. Otherwise, they are redirected to the editions page. @Mikxox @NielsPraet could one of you make sure this also works on your end?

Set landing page

---

frontend/pages/[editionName]/projects.tsx
frontend/pages/[editionName]/students.tsx
frontend/pages/_app.tsx
frontend/pages/editions.tsx
frontend/pages/login.tsx
frontend/pages/register.tsx
frontend/pages/users.tsx
frontend/pages/wait.tsx

This PR adds some better titles and a nice favicon to our application.
Closes #331

refactor: add informative title to pages

---

backend/src/main/kotlin/be/osoc/team1/backend/controllers/StudentController.kt
backend/src/main/kotlin/be/osoc/team1/backend/entities/Student.kt
backend/src/test/kotlin/be/osoc/team1/backend/unittests/StudentControllerTests.kt
docs/osoc.yaml

**Breaking change checklist**:

Added other views

---

backend/src/main/kotlin/be/osoc/team1/backend/controllers/CommunicationController.kt

Fix communication

---

backend/src/main/kotlin/be/osoc/team1/backend/controllers/ControllersUtil.kt
backend/src/main/kotlin/be/osoc/team1/backend/controllers/StudentController.kt
backend/src/test/kotlin/be/osoc/team1/backend/unittests/StudentControllerTests.kt
docs/osoc.yaml

Getstudent view

---

frontend/components/StudentSidebar.tsx
frontend/components/student/StudentHolder.tsx
frontend/components/student/StudentView.tsx
frontend/components/students/StudentTile.tsx
frontend/lib/conversionUtils.ts
frontend/lib/types.ts
frontend/pages/[editionName]/students.tsx

Update frontend to make use of #326 
This closes #342 
~~I started from #332 to be able to start implementing this before merge was done.
I'll open this as soon as #332 is merged since everything should already work as intended.~~
All functionality is present & should work.
~~Will need to be fixed again once #349 is merged~~ Done

Frontend reduce student data

---

frontend/pages/index.tsx
frontend/pages/login.tsx

Redirect on index page
Active edition? Reroute to projects page
No active edition? 
- Disabled Role? Wait Page
- Coach Role? Users Page
- Admin Role? Editions Page

feat: reroute on index page

---

docker/subpopulate.py

Closes #368 
More variety in the population script for the demo

Updated popscript

---

backend/src/main/kotlin/be/osoc/team1/backend/exceptions/InvalidTokenException.kt

Changed status code so frontend can catch it

Changed statuscode

---

frontend/pages/index.tsx

This PR fixes a small issue where didn't get properly routed to the login page if no user was stored in memory

Fix rerouting on index page

---

backend/src/main/kotlin/be/osoc/team1/backend/controllers/StudentController.kt
backend/src/main/kotlin/be/osoc/team1/backend/entities/Student.kt
backend/src/test/kotlin/be/osoc/team1/backend/unittests/StudentControllerTests.kt
docs/osoc.yaml
frontend/components/StudentSidebar.tsx

This PR adds a filter that filters on only assigned students as requested by Miet.
**New feature checklist**:

Only assigned filter

---

docker/subpopulate.py

More info for students in popscript

Better students

---

backend/src/main/kotlin/be/osoc/team1/backend/services/EmailService.kt
backend/src/test/kotlin/be/osoc/team1/backend/unittests/ForgotPasswordServiceTests.kt

The advantage of doing this is that it allows us to mock things like the environment variables and allows us to remove a function from the `EmailService` that only existed for use in tests.

Use injected environment and emailsender to improve testing

---

frontend/components/student/StudentView.tsx

Motivation for suggestion is not required

---

backend/src/main/kotlin/be/osoc/team1/backend/entities/Project.kt
backend/src/main/kotlin/be/osoc/team1/backend/entities/Student.kt
backend/src/main/kotlin/be/osoc/team1/backend/entities/User.kt

Closes #374
Closes #375 
This also fixes, if you try to delete a position, it also deletes the assignment.

Cascade deletion bugs

---

frontend/components/StudentSidebar.tsx
frontend/hooks/useAxiosAuth.ts
frontend/lib/requestUtils.ts
frontend/package.json
frontend/pages/[editionName]/communications.tsx
frontend/pages/[editionName]/projects.tsx
frontend/pages/[editionName]/students.tsx
frontend/pages/editions.tsx
frontend/pages/users.tsx
frontend/yarn.lock

This fixes the reloading issues,
I thing everything works now.
I also added a mutex around refreshing, to fix using different axiosauth instances since the sidebar & main view in for example projects would not share the same refresh request promise and would still fail.
I also had to add an ignore 401 error due to this.
~~I noticed the users & editions page doesn't work after a reload, I'll be fixing that~~ done

Fix reloading issues

---

frontend/components/projects/ProjectConflict.tsx
frontend/components/projects/ProjectTile.tsx
frontend/lib/requestUtils.ts
frontend/pages/[editionName]/projects.tsx

This pr should fix the conflict issues in #303 
I haven't been able to get the sorting error or the error on returning back to all conflicts,
so those might be fixed now but I'm not 100% sure since I did not specifically fix them.
Note: a resolved conflict stays in the list even after closing and re-opening the conflicts, this is intentional and changing this is only 1 line of code, so depending on what we prefer I'll change that back or not.

Conflict fixes

---

docker/populate
docker/subpopulate.py

Added seed

---

frontend/components/Error.tsx
frontend/components/projects/ProjectConflict.tsx
frontend/components/projects/ProjectTile.tsx
frontend/pages/[editionName]/communications.tsx
frontend/pages/[editionName]/projects.tsx
frontend/pages/[editionName]/students.tsx
frontend/pages/editions.tsx
frontend/pages/users.tsx

This PR updates the error component so you can close it yourself

feat: add closeable errors

---

frontend/components/StudentSidebar.tsx
frontend/components/editions/EditionCard.tsx
frontend/components/editions/EditionCreateForm.tsx
frontend/components/student/StudentView.tsx
frontend/pages/[editionName]/communications.tsx
frontend/pages/[editionName]/projects.tsx

Updates color contrasts of some buttons and text fields.

style: update color contrasts

---

frontend/components/communications/CommsTable.tsx
frontend/components/communications/CommsTableRow.tsx
frontend/pages/[editionName]/communications.tsx
frontend/pages/[editionName]/projects.tsx

Communications page now allows searching by name.
Conflicts will reset if you click on "show all projects" and then "show conflicts" again.

Comms search & conflicts reset

---

backend/src/main/kotlin/be/osoc/team1/backend/controllers/InviteController.kt
backend/src/main/kotlin/be/osoc/team1/backend/services/EmailService.kt
backend/src/main/kotlin/be/osoc/team1/backend/services/ForgotPasswordService.kt
backend/src/test/kotlin/be/osoc/team1/backend/unittests/EmailServiceTests.kt
backend/src/test/kotlin/be/osoc/team1/backend/unittests/ForgotPasswordServiceTests.kt
backend/src/test/kotlin/be/osoc/team1/backend/unittests/InviteControllerTests.kt
docs/osoc.yaml
frontend/pages/[editionName]/communications.tsx
frontend/pages/register.tsx
frontend/pages/users.tsx
frontend/tailwind.config.js

Closes #405 
Backend:
Frontend:

Add email invites

---

frontend/components/projects/ProjectTile.tsx

Better readable difference between positions

---

frontend/components/editions/EditionCreateForm.tsx

style: remove button to add an image as this isn't supported

---

frontend/components/projects/ProjectTile.tsx
frontend/styles/line.css

This makes the positions text on the projects page connect when a position is multiline.
closes #303

feat: make position text background connect

---

docker/populate
docker/subpopulate.py

Note: You do need to set all editions to inactive before you run a different edition.

feat: allow to make different edition

---

frontend/components/projects/ProjectTile.tsx
frontend/components/student/StudentView.tsx
frontend/lib/requestUtils.ts
frontend/pages/[editionName]/communications.tsx
frontend/pages/[editionName]/projects.tsx
frontend/pages/editions.tsx

Disable some UI elements when edition is not active

---

.github/workflows/deployment.yml

fix: env variables

---

.github/workflows/deployment.yml
frontend/components/projects/ProjectTile.tsx

Final final pr?

---

frontend/components/projects/ProjectTile.tsx

add extra check before rendering

---

frontend/components/projects/ProjectConflict.tsx
frontend/pages/[editionName]/projects.tsx

fix not passing property
